- name: variables from play level
  hosts: localhost
  taskd:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hello {{PERSON}}, Good{{WISHES}}"

#Passing the args from command line for the above variable.
#ansible-playbook -i inventory.ini -e ansible_user=centos -e ansible_password=DevOps321 -e "PERSON=Sivakumar -e "WISHES=Morning" 09-vars-from-args.yaml
