- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: print the person
    ansible.builtin.package:
      name: "{{item}}" #item is a default keyword
    loop:
    - git
    - mysql
    - postfic
    